name: Build sdist and wheels

on: workflow_dispatch

env:
  FORCE_COLOR: 1
  PIP_PROGRESS_BAR: 'off'

jobs:
  noarch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '>=3.10'
    - name: Update setup, install build
      run: python -m pip install --upgrade pip setuptools build
    - name: Create source distribution
      run: python -m build --sdist
    - name: Create universal wheel (no Cython)
      run: sseflags=none python -m build --wheel
    - name: Test universal wheel
      run: |
        python -m pip install numpy
        python -m pip install dist/*.whl
        cd ..
        python -m sseflags.benchmark
    - uses: actions/upload-artifact@v6
      with:
        name: noarch(${{ github.ref_name }})
        path: ./dist/*

  wheels:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-26-intel, windows-latest,
             ubuntu-24.04-arm, macos-26, windows-11-arm]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '>=3.10' # for cibuildwheel itself
    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel
    - name: Build wheels
      env:
        CIBW_PROJECT_REQUIRES_PYTHON: '==3.10.*'
      run: python -m cibuildwheel --output-dir wheels
    - uses: actions/upload-artifact@v6
      with:
        name: wheels(${{ github.ref_name }})${{ matrix.os }}
        path: ./wheels/*

  testAFP:
    needs: wheels
    runs-on: ubuntu-24.04-arm
    steps:
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '>=3.10'
    - name: Download wheel
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh run download -R '${{ github.repository }}' \
                        -n 'wheels(${{ github.ref_name }})ubuntu-24.04-arm'
        ls -Al
    - name: Install wheel
      run: python -m pip install *manylinux*.whl
    - name: Install QEMU 10.2
      # ubuntu-24.04 has only qemu-user_1:8.2.2 without FEAT_AFP
      run: |
        wget --no-verbose https://ports.ubuntu.com/pool/universe/q/qemu/qemu-user_10.2.1+ds-1ubuntu3_arm64.deb
        sudo dpkg --ignore-depends=ubuntu-virt -i *.deb
    - name: Run test in QEMU
      run: qemu-aarch64 -cpu max $(which python) -m sseflags.test
